use std::path::Path;

/// Observer trait for file change events generated by the agent.
pub trait OnFileChanged: Send + Sync + 'static {
    /// Called when the agent modifies or creates a file.
    fn on_file_changed(&self, path: &Path);
}

/// A no-op implementation of [`OnFileChanged`].
#[derive(Debug)]
pub struct DefaultFileObserver;

impl OnFileChanged for DefaultFileObserver {
    fn on_file_changed(&self, _path: &Path) {}
}

/// Extension wrapper for storing [`OnFileChanged`] in a tool context.
#[derive(Clone)]
pub struct OnFileChangedExt(pub std::sync::Arc<dyn OnFileChanged>);

impl std::fmt::Debug for OnFileChangedExt {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("OnFileChangedExt")
            .field(&"<dyn OnFileChanged>")
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::sync::atomic::{AtomicUsize, Ordering};

    struct CountingObserver {
        calls: Arc<AtomicUsize>,
    }

    impl OnFileChanged for CountingObserver {
        fn on_file_changed(&self, _path: &Path) {
            self.calls.fetch_add(1, Ordering::SeqCst);
        }
    }

    #[test]
    fn default_observer_is_noop() {
        let obs = DefaultFileObserver;
        // Must not panic and must not observe anything.
        obs.on_file_changed(Path::new("/tmp/x.md"));
    }

    #[test]
    fn custom_observer_is_called_through_ext() {
        let calls = Arc::new(AtomicUsize::new(0));
        let ext = OnFileChangedExt(Arc::new(CountingObserver {
            calls: calls.clone(),
        }));
        ext.0.on_file_changed(Path::new("/a.md"));
        ext.0.on_file_changed(Path::new("/b.md"));
        assert_eq!(calls.load(Ordering::SeqCst), 2);
    }
}
