//! Property-based tests for the YAML frontmatter parser.
//!
//! The YAML frontmatter is parsed by
//! [`crate::markdown::Document::new`] + [`Document::front_matter`],
//! which is also the entry point for the `read_yaml_header` /
//! `write_yaml_header` agent tools. The parser is the project's
//! only deserialisation surface for user-supplied content that
//! came from disk; a malformed-YAML panic in the parser would
//! land a user in a crashed editor.
//!
//! Per AGENTS.md RUST-058 the markdown parser is egui-free, so
//! the proptest can live as a sidecar of `yaml_header.rs` (the
//! parser itself is in `crate::markdown`).
//!
//! # Properties under test
//!
//! 1. **Panic-freedom**: any random byte string passed to
//!    `Document::new(...).front_matter()` returns `Result` or
//!    `Option` — never panics. Proptest is configured to run
//!    `cases = 256` per property with `cases > 0` shrinking to
//!    find the minimum failing input. A single panic surfaces
//!    a parser bug that the existing example-based tests
//!    wouldn't catch.
//! 2. **Round-trip for valid frontmatter**: a YAML block
//!    generated by `proptest!`'s `any::<(String, Value)>`
//!    strategy (a `key: value` pair) always round-trips
//!    through `Document::new(content).front_matter()` and back
//!    to the same `key: value` pair. The pair is small and
//!    fast, but it covers the full key/value surface
//!    (string, integer, float, bool, sequence, mapping).
//! 3. **`---` closing delimiter is required**: a frontmatter
//!    block without a closing `---` is not recognised as
//!    frontmatter (the parser treats the entire block as body
//!    text). This is the spec behaviour; the proptest guards
//!    against a future regression that loosens the
//!    "matching closing fence" rule.

use crate::utils::markdown::parse_front_matter;
use proptest::prelude::*;

/// Strategy: a single frontmatter key/value pair. Keys are
/// short ASCII identifiers; values are short alphanumeric
/// tokens (no whitespace, no YAML 1.2 reserved indicators,
/// no special syntax). The strategy is intentionally narrow
/// — the goal is to surface a parser panic on the *common*
/// shape, not to test the full YAML 1.2 surface. The
/// whitespace-stripping / reserved-char edge cases are the
/// `frontmatter_parser_never_panics` property's job.
fn yaml_value_strategy() -> impl Strategy<Value = (String, String)> {
    (
        prop::string::string_regex(r"[a-z][a-z0-9_]{0,15}").unwrap(),
        prop::string::string_regex(r"[a-zA-Z][a-zA-Z0-9_]{0,19}").unwrap(),
    )
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    /// Property 1: panic-freedom on any random byte string.
    /// `parse_front_matter(bytes)` must return `None`
    /// or `Some(...)`; it must never panic. The byte string
    /// is constrained to valid UTF-8 (the parser is a UTF-8
    /// parser; non-UTF-8 input is a different layer) but
    /// otherwise arbitrary — the strategy emits printable ASCII
    /// with newlines so the parser sees every line-position
    /// the frontmatter detector cares about.
    #[test]
    fn frontmatter_parser_never_panics_on_arbitrary_input(
        body in prop::string::string_regex(r"[\x20-\x7E\n]{0,200}").unwrap()
    ) {
        let _ = parse_front_matter(&body);
    }

    /// Property 2: a key/value frontmatter block round-trips
    /// through `parse_front_matter(content)`. The
    /// key and value are arbitrary (within the printable-ASCII
    /// range); the test constructs a `---\n{key}: {value}\n---\n`
    /// block, parses it, and asserts the same key/value pair
    /// comes back. The contract under test is "the parser does
    /// not lose information on the simple `key: scalar` form".
    #[test]
    fn frontmatter_roundtrips_key_value_pair(
        (key, value) in yaml_value_strategy()
    ) {
        let body = format!("---\n{key}: {value}\n---\nbody\n");
        let fm = parse_front_matter(&body).expect("frontmatter should parse");
        let v = fm.yaml.get(&key).expect("key should round-trip");
        let s = v.as_str().map(String::from)
            .or_else(|| v.as_i64().map(|n| n.to_string()))
            .or_else(|| v.as_f64().map(|n| n.to_string()))
            .or_else(|| v.as_bool().map(|b| b.to_string()))
            .unwrap_or_default();
        if s != value {
            prop_assert!(
                false,
                "key={} parsed value mismatch: input={:?} got={:?}",
                key,
                value,
                s
            );
        }
    }

    /// Property 3: a frontmatter block without the closing
    /// `---` is NOT parsed as frontmatter. The parser treats
    /// the entire file (including the unclosed `---` line) as
    /// body.
    #[test]
    fn unclosed_frontmatter_is_not_parsed_as_frontmatter(
        (key, value) in yaml_value_strategy()
    ) {
        let body = format!("---\n{key}: {value}\nthis is body, not yaml\n");
        prop_assert!(
            parse_front_matter(&body).is_none(),
            "unclosed frontmatter should be ignored"
        );
    }
}
