//! Agent-domain events and prompt type — the structured payloads that cross
//! the agent↔UI seam on `Bus<AgentEvent>` (agent→UI) and
//! `Sender<AgentPrompt>` (UI→agent).
//!
//! Requirements: AGENT-005 (no UI channel in agent), AGENT-008 (session
//! identity), AGENT-010 (structured deltas), AGENT-011 (no running buffer).
//! See `specs/003-agent-ui-seam-refactor/contracts/agent-seam.md` for the full
//! contract.
//!
//! Unit tests live in the sibling `events_tests.rs` sidecar.

use chrono::{DateTime, Local};
use schemars::JsonSchema;
use serde::Deserialize;
use serde::Serialize;
use serde_json::Value;
use std::collections::HashSet;
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::AtomicBool;
use uuid::Uuid;

/// Direction of a debug entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum DebugEntryKind {
    /// Net-new messages sent to the LLM this turn (delta vs previous outgoing).
    Outgoing,
    /// Full JSON response received from the LLM.
    Incoming,
    /// Tool results returned after execution.
    ToolResults,
}

/// Row type — distinguishes normal collapsible entries from session dividers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum DebugEntryRow {
    /// A normal debug entry (collapsible, with content).
    Entry,
    /// A non-interactive session-divider row.
    SessionBoundary,
}

/// A single debug log entry capturing the raw content of one part of one turn.
///
/// Session identity lives on the enclosing `AgentEvent::DebugEntry { session_id }`
/// variant — this struct no longer carries its own `session` field (migration
/// step 10, data-model.md §4).
#[derive(Debug, Clone, Serialize)]
pub struct AgentDebugEntry {
    /// Monotonic turn number within the session (1-based; 0 for session boundaries).
    pub turn: usize,
    /// When the entry was created.
    pub timestamp: DateTime<Local>,
    /// Kind of the entry.
    pub kind: DebugEntryKind,
    /// One-line summary shown in the collapsed row.
    pub summary: String,
    /// Full JSON content shown when expanded. `None` for SessionBoundary.
    pub content: Option<serde_json::Value>,
    /// Whether this row is a session boundary.
    pub row_type: DebugEntryRow,
}

/// Token usage statistics returned by the LLM API.
///
/// Covers the OpenAI standard fields and the common sub-details (cached input
/// tokens, reasoning tokens emitted by o-series models). For Anthropic-style
/// endpoints, `input_tokens` and `output_tokens` from the response are mapped
/// onto `prompt_tokens` and `completion_tokens` respectively by the parser.
#[derive(Debug, Clone, Default, serde::Deserialize, serde::Serialize)]
pub struct TokenUsageInfo {
    /// Tokens consumed by the prompt (i.e. the full conversation context
    /// sent on this turn). On Anthropic-style responses this is the
    /// `input_tokens` value.
    pub prompt_tokens: u64,
    /// Tokens generated by the model on this turn. On Anthropic-style
    /// responses this is the `output_tokens` value.
    pub completion_tokens: u64,
    /// Total tokens reported by the API (`prompt_tokens + completion_tokens`
    /// for OpenAI, may be reported independently by other providers).
    pub total_tokens: u64,
    /// Subset of `prompt_tokens` served from cache, if the provider reports
    /// it (OpenAI `prompt_tokens_details.cached_tokens`).
    pub cached_tokens: Option<u64>,
    /// Subset of `completion_tokens` spent on internal reasoning, if the
    /// provider reports it (OpenAI `completion_tokens_details.reasoning_tokens`).
    pub reasoning_tokens: Option<u64>,
}

/// Input message: UI → agent on `std::sync::mpsc::Sender<AgentPrompt>`.
///
/// The UI mints `session_id: Uuid::new_v4()` for a new session and reuses it
/// for continuation prompts in the same session (FR-008).
pub struct AgentPrompt {
    /// Identity of the session this prompt belongs to.
    pub session_id: Uuid,
    /// The user's prompt text. MUST be non-empty after trim.
    pub text: String,
    /// Pre-assembled system-prompt message blocks. Built by the
    /// submitter (UI or batch executor) via
    /// [`crate::app::prompts::build_system_prompts`]. The agent run
    /// loop no longer constructs these — it just forwards the
    /// blocks as `role=system` messages ahead of the user turn.
    pub system_prompts: Vec<String>,
    /// UI selection context passed through to tools.
    pub active_file: Option<PathBuf>,
    /// UI selection context passed through to tools.
    pub active_dir: Option<PathBuf>,
    /// UI selection context passed through to tools.
    pub selected_files: HashSet<PathBuf>,
    /// Shared cancel flag for the session. The UI sets this to `true`
    /// to abort the in-progress turn (FR-015). The driver passes it
    /// into the `AgentContext` so the agent loop can poll it.
    pub cancel_flag: Arc<AtomicBool>,
}

/// Typed agent status — replaces the old `AgentEvent::Status(String)` with
/// structured states. Carried inside [`crate::app::events::AgentEvent::Status`].
#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub enum AgentStatus {
    /// Waiting for the LLM to return a response.
    AwaitingLlm,
    /// Executing tool calls returned by the LLM.
    ExecutingTools,
    /// The turn loop ended normally (LLM returned a final response).
    Done,
}

impl AgentStatus {
    /// Human-readable status string for the UI status label (replaces
    /// the old `AgentEvent::Status(String)` free-form strings).
    pub fn display_string(&self) -> &'static str {
        match self {
            AgentStatus::AwaitingLlm => "Waiting for LLM completions...",
            AgentStatus::ExecutingTools => "Executing tools...",
            AgentStatus::Done => "Done",
        }
    }
}

/// A side effect produced by a tool execution that the UI must reissue as a
/// filesystem event. Returned by `ToolExecutor::execute_all` and republished
/// by the agent as `AgentEvent::ToolSideEffect`.
#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub enum ToolSideEffect {
    /// A file was created by a tool (e.g. `create_note`).
    FileCreated {
        /// Absolute path of the created file.
        path: PathBuf,
        /// Tags extracted from the note's front matter.
        tags: Vec<String>,
    },
    /// A file was changed or modified by a tool.
    FileChanged {
        /// Absolute path of the changed file.
        path: PathBuf,
    },
}

/// A single sub-agent tool call captured inside a `WebDelegateResponse` —
/// structured per-call data replacing the old string-based trace field.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct DelegateToolCall {
    /// The tool function name (e.g. `browser_navigate`).
    pub name: String,
    /// The arguments passed to the tool, as JSON.
    pub args: Value,
    /// The result returned by the tool, as JSON.
    pub result: Value,
}

// ---------------------------------------------------------------------------
// Observer Pattern for AgentEvent
// ---------------------------------------------------------------------------

/// Trait for receiving `AgentEvent`s from the agent loop. Decouples the
/// agent from the concrete transport (like `tokio::sync::broadcast::Sender`).
/// The observer is scoped to a specific session.
pub trait AgentEventObserver: Send + Sync {
    /// Emitted when a new session starts.
    fn on_session_started(&self);
    /// Emitted when a session finishes with full history.
    fn on_session_finished(&self, history: Vec<serde_json::Value>);
    /// Emitted when turn status changes.
    fn on_status(&self, status: AgentStatus);
    /// Emitted when reasoning/thinking tokens arrive.
    fn on_thinking(&self, text: String);
    /// Emitted when content delta tokens arrive.
    fn on_content_delta(&self, text: String);
    /// Emitted before tool execution starts.
    fn on_tool_call_started(&self, id: String, name: String, args: serde_json::Value);
    /// Emitted after tool execution completes with its result.
    fn on_tool_result(&self, id: String, name: String, result: serde_json::Value);
    /// Emitted when a tool produces a side effect.
    fn on_tool_side_effect(&self, effect: ToolSideEffect);
    /// Emitted when a debug entry is created.
    fn on_debug_entry(&self, entry: AgentDebugEntry);
    /// Emitted when token usage statistics are received.
    fn on_token_usage(&self, usage: TokenUsageInfo);
    /// Emitted when session execution fails with an error.
    fn on_failed(&self, error: String);
}

// ---------------------------------------------------------------------------
// Tests live in the sibling `events_tests.rs` sidecar.
// ---------------------------------------------------------------------------

#[cfg(test)]
#[path = "events_tests.rs"]
mod tests;
