//! Canonical LLM-facing strings for cursor-based pagination.
//!
//! Used by `search_email`. The cursor is an opaque string that the
//! tool returns and the LLM passes back unchanged. The cache key
//! for the underlying shared `ToolCache` is the same string.

/// `cursor` field description. Used on both the input and output
/// `cursor` fields of `search_email` because the LLM passes back
/// whatever the tool returned.
pub const FIELD_CURSOR_DESCRIPTION: &str = "Opaque pagination token. Pass it back unchanged in a follow-up call to get the next page. Generated by the tool on the first call. Absent when the result set is exhausted.";

/// Description for `search_email`. Replaces the offset/limit
/// canonical paragraph because the cursor flow is fundamentally
/// different. The full tool description is this paragraph + the
/// domain sentence in `strings::jmap::SEARCH_EMAIL_DOMAIN`.
pub const SEARCH_EMAIL_CANONICAL_DESCRIPTION: &str = "Searches email by any combination of keyword, folder, date range, sender, recipient, unread, or flagged. Filters combine with AND. At least one filter MUST be provided. The first call returns up to 100 matching emails plus a `cursor`; pass the same `cursor` back in a follow-up call to get the next page. The full server result set is cached for 5 minutes. When the result set is exhausted, the response includes a `hint` and no `cursor`.";
