//! Legacy `BackgroundMessage` enum — the monolithic background-to-UI event type.
//!
//! This is the god-enum that the architecture review (P1-6) flagged for
//! replacement. Producers across the background subsystem still send
//! these; the UI matches on the flat enum. A typed replacement lives in
//! [`crate::bus::events::typed`] (`BackgroundEvent` + per-domain
//! sub-enums) and is being migrated to. Until that migration is
//! complete, every variant defined here remains load-bearing.

use crate::background::BackgroundLogEntry;
use notify::RecommendedWatcher;
use serde_json::Value;
use std::path::PathBuf;

/// Token usage statistics returned by the LLM API.
///
/// Covers the OpenAI standard fields and the common sub-details (cached input
/// tokens, reasoning tokens emitted by o-series models). For Anthropic-style
/// endpoints, `input_tokens` and `output_tokens` from the response are mapped
/// onto `prompt_tokens` and `completion_tokens` respectively by the parser.
#[derive(Debug, Clone, Default, serde::Deserialize)]
pub struct TokenUsageInfo {
    /// Tokens consumed by the prompt (i.e. the full conversation context
    /// sent on this turn). On Anthropic-style responses this is the
    /// `input_tokens` value.
    pub prompt_tokens: u64,
    /// Tokens generated by the model on this turn. On Anthropic-style
    /// responses this is the `output_tokens` value.
    pub completion_tokens: u64,
    /// Total tokens reported by the API (`prompt_tokens + completion_tokens`
    /// for OpenAI, may be reported independently by other providers).
    pub total_tokens: u64,
    /// Subset of `prompt_tokens` served from cache, if the provider reports
    /// it (OpenAI `prompt_tokens_details.cached_tokens`).
    pub cached_tokens: Option<u64>,
    /// Subset of `completion_tokens` spent on internal reasoning, if the
    /// provider reports it (OpenAI `completion_tokens_details.reasoning_tokens`).
    pub reasoning_tokens: Option<u64>,
}

/// Monolithic background-to-UI message. Replaced piecemeal by
/// [`crate::bus::events::typed::BackgroundEvent`]; see the architecture
/// review (P1-6) and the migration comment in that module.
#[derive(Debug)]
pub enum BackgroundMessage {
    FileParsed {
        path: PathBuf,
        tags: Vec<String>,
    },
    DirParsed {
        path: PathBuf,
    },
    Finished(RecommendedWatcher),
    FinishedWithoutWatcher,
    FileModified {
        path: PathBuf,
        tags: Vec<String>,
    },
    FileDeleted {
        path: PathBuf,
    },

    AgentStatus(String),
    AgentThinking(String),
    AgentResponse(String),
    AgentFinished(Vec<Value>),
    AgentFailed(String),
    /// Emitted after every LLM turn that returns a `usage` block. The UI can
    /// use `prompt_tokens` as the current context-window occupancy for that
    /// turn, and accumulate the other fields to track spend.
    AgentTokenUsage(TokenUsageInfo),

    LogEntry(BackgroundLogEntry),

    /// File content loaded from a background thread.
    FileLoaded {
        path: PathBuf,
        content: Result<String, String>,
    },
}
