//! Table of Contents entry — a stable heading descriptor used by the
//! TOC builder, the tab manager, and the right panel renderer.
//!
//! `title` and `level` come from the Markdown parser; `id` is a
//! stable string identifier generated by [`super::build_toc`].
//! The UI layer converts it to `egui::Id::new(&id)` at render time.

use core::fmt;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ToCEntry {
    /// Heading text, trimmed of markdown decoration.
    pub title: String,
    /// Heading depth (1 == H1, 2 == H2, …).
    pub level: u32,
    /// Stable string identifier for the heading.
    /// The first `"Intro"` has `id == "Intro"`; the second has
    /// `id == "Intro#1"`; the third `"Intro#2"`, etc.
    pub id: String,
}

impl ToCEntry {
    /// Construct a new entry.
    pub fn new(title: impl Into<String>, level: u32, id: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            level,
            id: id.into(),
        }
    }
}

impl fmt::Display for ToCEntry {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} (H{})", self.title, self.level)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_toc_entry_new() {
        let e = ToCEntry::new("Intro", 1, "Intro");
        assert_eq!(e.title, "Intro");
        assert_eq!(e.level, 1);
        assert_eq!(e.id, "Intro");
    }

    #[test]
    fn test_toc_entry_display() {
        let e = ToCEntry::new("Intro", 1, "Intro");
        assert_eq!(format!("{e}"), "Intro (H1)");
    }
}
