use std::path::Path;

/// Observer trait for file change events generated by the agent.
pub trait OnFileChanged: Send + Sync + 'static {
    /// Called when the agent modifies or creates a file.
    fn on_file_changed(&self, path: &Path);
}

/// A no-op implementation of [`OnFileChanged`].
pub struct DefaultFileObserver;

impl OnFileChanged for DefaultFileObserver {
    fn on_file_changed(&self, _path: &Path) {}
}

/// Extension wrapper for storing [`OnFileChanged`] in a tool context.
#[derive(Clone)]
pub struct OnFileChangedExt(pub std::sync::Arc<dyn OnFileChanged>);
