use crate::bus::events::file::FileEventKind;
use std::path::Path;

/// Observer trait for file change events generated by the agent.
pub trait OnFileChanged: Send + Sync + 'static {
    /// Called when the agent modifies, creates, or deletes a file/directory.
    fn on_file_changed(&self, path: &Path, kind: FileEventKind);
}

pub struct DefaultFileObserver;

impl OnFileChanged for DefaultFileObserver {
    fn on_file_changed(&self, _path: &Path, _kind: FileEventKind) {}
}

#[derive(Clone)]
pub struct OnFileChangedExt(pub std::sync::Arc<dyn OnFileChanged>);
